# Generated by Django 4.2.29 on 2026-03-09 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сессия кілті')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Себет',
                'verbose_name_plural': 'Себеттер',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Атауы')),
                ('slug', models.SlugField(unique=True, verbose_name='Сілтеме')),
            ],
            options={
                'verbose_name': 'Санат',
                'verbose_name_plural': 'Санаттар',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Қала атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Қала',
                'verbose_name_plural': 'Қалалар',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=50, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Мекенжай')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('status', models.CharField(choices=[('new', 'Жаңа'), ('processing', 'Өңделуде'), ('completed', 'Орындалды'), ('cancelled', 'Бас тартылды')], default='new', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Жалпы баға')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Қолданылған жеңілдік (%)')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Қаралды ма?')),
                ('bonus_points_used', models.PositiveIntegerField(default=0, verbose_name='Қолданылған баллдар')),
                ('bonus_points_earned', models.PositiveIntegerField(default=0, verbose_name='Жинақталған баллдар')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.city', verbose_name='Қала')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Атауы')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бағасы')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Суреті')),
                ('is_new_collection', models.BooleanField(default=False, verbose_name='Жаңа топтама')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Санаты')),
            ],
            options={
                'verbose_name': 'Киім',
                'verbose_name_plural': 'Киімдер',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Жинақталған сома')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Бонус баллдары')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пайдаланушы профилі',
                'verbose_name_plural': 'Пайдаланушы профильдері',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Өлшем')),
                ('color', models.CharField(max_length=30, verbose_name='Түс')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Қалдық')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Киім')),
            ],
            options={
                'verbose_name': 'Нұсқа',
                'verbose_name_plural': 'Нұсқалар',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Саны')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сатып алу бағасы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Тапсырыс')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant', verbose_name='Нұсқа')),
            ],
            options={
                'verbose_name': 'Тапсырыс элементі',
                'verbose_name_plural': 'Тапсырыс элементтері',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Атауы (админ үшін)')),
                ('banner_title', models.CharField(blank=True, max_length=200, verbose_name='Баннер тақырыбы')),
                ('banner_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Баннер асты мәтіні')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Сурет')),
                ('link', models.CharField(blank=True, help_text='Бос қалдырсаңыз, баннер басылмайды', max_length=500, verbose_name='Сілтеме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('category', models.ForeignKey(blank=True, help_text='Егер категория бетіне сілтеме болса, таңдаңыз', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннерлер',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Саны')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Себет')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant', verbose_name='Нұсқа')),
            ],
            options={
                'verbose_name': 'Себет элементі',
                'verbose_name_plural': 'Себет элементтері',
                'unique_together': {('cart', 'variant')},
            },
        ),
    ]
