# Generated by Django 4.2.29 on 2026-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Баннер асты мәтіні'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_subtitle_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Баннер асты мәтіні'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Баннер асты мәтіні'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Баннер тақырыбы'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Баннер тақырыбы'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Баннер тақырыбы'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Атауы'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Атауы'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Атауы'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Қала атауы'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Қала атауы'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Қала атауы'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Сипаттамасы'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Сипаттамасы'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Сипаттамасы'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Атауы'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Атауы'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Атауы'),
        ),
    ]
